feat(organizations): add organizations model, organization members an…
platanus/lakatan pull request #108
Opened 2020-11-17 14:39 UTC by fhohlberg

…d documentation

2020-11-17 15:50 UTC, smargozzini requested changes

2020-11-17 15:50 UTC, smargozzini commented on app/controllers/api/v1/integrations_controller.rb
> +    respond_with Integration.create!(slack_token: token.access_token, salt: salt, slack_workspace_name: token.team.name, organization_id: params["integration"]["organization_id"])
el param de la `organiztion_id` lo sacaría de `integration_params`, no directamente de los params

2020-11-17 15:50 UTC, smargozzini commented on app/controllers/api/v1/org_members_controller.rb
> +  end
donde usas esto?

2020-11-17 15:50 UTC, smargozzini commented on spec/models/org_member_spec.rb
> +end
falta este test

2020-11-17 15:50 UTC, smargozzini commented on spec/models/organization_spec.rb
> +end
falta este test

2020-11-18 15:27 UTC, fhohlberg commented on app/controllers/api/v1/org_members_controller.rb
> +  end
no se usa, venia por defecto con power api, queda eliminado

2020-11-18 15:29 UTC, fhohlberg commented on app/controllers/api/v1/integrations_controller.rb
> +    respond_with Integration.create!(slack_token: token.access_token, salt: salt, slack_workspace_name: token.team.name, organization_id: params["integration"]["organization_id"])
ok!

2020-11-20 12:41 UTC, smargozzini approved these changes

2020-11-22 15:47 UTC, merged