fix(mailers): change email to spanish and fix welcome email
platanus/lakatan pull request #116
Opened 2020-11-22 21:03 UTC by fhohlberg

2020-11-22 21:32 UTC, ClaudioPrieto commented on app/jobs/send_user_mail_job.rb
> +    if (user.encrypted_password != "")
No entiendo este cambio, segun yo estaba funcionando bien antes.

2020-11-22 23:29 UTC, fhohlberg commented on app/jobs/send_user_mail_job.rb
> +    if (user.encrypted_password != "")
no! el atributo password era siempre null, y entraba siembre en el segundo if, pero quedo arreglado el error

2020-11-24 13:01 UTC, mrafaeli requested changes
Hola! Se ve super, te dejo unos comentarios chicos respecto a los textos.

2020-11-24 13:01 UTC, mrafaeli commented on app/views/user_notifier_mailer/send_signup_email.html.erb
> +    <p>¡Gracias por unirse a Lakatan, ahora ya puede iniciar sesión!</p>
Como sugerencia, en general trataría de no ser tan formal con el usuario.

`Muchas gracias por registrarte en Lakatan`
`Gracias por unirte a Lakatan, ahora ya puedes iniciar sesión`

2020-11-25 23:40 UTC, merged