Doc fix
platanus/lakatan pull request #119
Opened 2020-11-23 12:34 UTC by fhohlberg

2020-11-23 17:45 UTC, jgmontoya requested changes
En general bien, sacaría lo de los tasks a un método para evitar que el `create` crezca tanto y que quede más claro en general

2020-11-23 17:45 UTC, jgmontoya commented on app/controllers/api/v1/teams_controller.rb
> +    end
Creo que esto quedaría mejor en un método aparte

2020-11-23 17:45 UTC, jgmontoya commented on swagger/v1/swagger.json
> +                          "debe ser mayor que o igual a 1"
Creo que sería mejor ser más consistente con el idioma a utilizar

2020-11-23 17:45 UTC, jgmontoya commented on swagger/v1/swagger.json
> +                          "debe existir"
Lo mismo acá

2020-11-25 03:45 UTC, jgmontoya commented on app/controllers/api/v1/teams_controller.rb
> -    end
esto lo quitaste pero no quedó como un método aparte, ya no se necesita?

2020-11-25 03:45 UTC, jgmontoya commented on app/models/integration.rb
> +  validates :organization_id, presence: { message: 'Can not be blank.' }
es algo mínimo pero mejor "can't" o no?

2020-11-25 03:45 UTC, jgmontoya commented on app/models/org_member.rb
> +  validates :user_id, :user_slack_id, :organization_id, presence: { message: 'Can not be blank.' }
lo mismo

2020-11-25 03:45 UTC, jgmontoya commented on app/models/organization.rb
> +  validates :name, presence: { message: 'Can not be blank.' }
y acá

2020-11-25 03:45 UTC, jgmontoya commented on app/models/slack_change.rb
> +  validates :status, presence: { message: 'Can not be blank.' }
.

2020-11-25 03:45 UTC, jgmontoya commented on app/models/team.rb
> +  validates :name, presence: { message: 'Can not be blank.' }
same

2020-11-25 03:45 UTC, jgmontoya commented on config/locales/en.yml
> +        greater_than_or_equal_to: "Must be greater or equal to 1."  # Applies to all other models
Quitaría el comentario

2020-11-25 03:46 UTC, jgmontoya commented
Veo que tienes algunos conflictos también, para que recuerdes echarles un ojo

2020-11-25 12:39 UTC, fhohlberg commented on app/controllers/api/v1/teams_controller.rb
> -    end
ahi quedó agregado

2020-11-25 13:29 UTC, jgmontoya approved these changes

2020-11-25 16:51 UTC, merged