Gmail groups
platanus/lakatan pull request #236
Opened 2021-01-19 21:01 UTC by yuval-linker

### Contexto
En Lakatan existen equipos con miembros, cosa muy parecida a [Google Groups](https://support.google.com/groups/answer/46601?hl=es&ref_topic=9216). Es por esto que se quiere dar la opción de sincronizar los grupos de Lakatan con los grupos de Google Workspace
### Qué se está haciendo
Se agrega la funcionalidad de poder sincronizar los grupos de Lakatan con google para poder crear grupos de mails. Para esto:

- Se agrega la gema `google-api-client` para utilizar la `admin SDK API`
- Se añade un cliente para poder ocupar la API
- Se añaden 5 comandos para crear y eliminar tanto grupos como miembros
- Se añaden observers para que la creación y eliminación sean automáticas al crear grupos o modificar los miembros en Lakatan
- Una página para poder controlar la integración de esta funcionalidad
- Un endpoint para poder manejar la autoriazción con OAuth 2.0 y Google
- Dos nuevas columnas en las integraciones para guardar la credenciales y el dominio
- Los tests correspondientes
#### En particular hay que revisar

- Buen diseño de la solución, siguiendo los mejores patrones de diseño para este problema en particular.
- Comandos y Observers bien definidos
- Cliente bien definido

---
### Info Adicional
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/69929590/105092614-3798b300-5a80-11eb-8baf-f46b2d2322ff.gif)

2021-01-19 21:01 UTC, yuval-linker commented
![](https://github.trello.services/images/mini-trello-icon.png) [Conectar con Directory API](https://trello.com/c/bZBOQwse/181-conectar-con-directory-api)

2021-01-19 23:34 UTC, jgmontoya requested changes
Otro patrón aparte de los comandos es el de los servicios. Es parecido y a veces no es tan obvio el si uno debería seguir uno u el otro. En este caso creo que se ajusta mejor a lo que estás haciendo, un indicador de eso es que tienes muchos comandos con acciones relacionadas (todos hacen algo sobre los grupos de google).

Te recomiendo que le eches un ojo a este post: https://blog.platan.us/services-commands-y-otros-poderosos-patrones-en-rails-27c2d3aa7c2e

Aparte de eso, creo que el `GoogleGroupsController` tiene demasiada lógica, pondría todo lo que tenga que ver con la autenticación y credenciales en un cliente y trataría de dejar el controlador más chico y que haga llamados a este cliente.

2021-01-19 23:34 UTC, jgmontoya commented on app/observers/member_observer.rb
> +end
No estoy del todo seguro si acá vale la pena usar observers, se podrían usar directamente los callbacks en el modelo. Le preguntaría a Leandro

2021-01-19 23:34 UTC, jgmontoya commented on app/observers/org_member_observer.rb
> +    @integration ||= Integration.find_by(organization_id: object.organization_id)
También funciona encadenándolas: `object.organization.integration`

2021-01-19 23:34 UTC, jgmontoya commented on app/observers/org_member_observer.rb
> +    User.find(object.user_id).email
Acá igual: `object.user`

2021-01-19 23:34 UTC, jgmontoya commented on config/routes.rb
> +  get '/oauth2callback' => 'google_groups#auth'
No me gusta mucho cómo se llama esta ruta, si después otra integración usa oauth2 va a quedar muy raro

2021-01-19 23:34 UTC, jgmontoya commented on app/javascript/router/index.js
> +  },
Me confundió un poco que se llame gmail esto (tanto la ruta como el componente), ¿debería ser 'google' o no?

2021-01-20 13:27 UTC, yuval-linker commented on app/observers/member_observer.rb
> +end
Le pregunté a Leandro y me dijo que los observers se hacen cuando uno quiere hacer algo en los callbacks relacionado al modelo pero no es del modelo. La idea es que los observers los puedes apagar para los tests pero los callbacks no. Entonces no quiero que se cree un grupo de google cada vez que se haga un equipo en los tests asi que esta bien usar observers.

2021-01-20 16:18 UTC, yuval-linker commented on db/migrate/20210114192244_add_org_domain_to_integrations.rb
> +    add_column :integrations, :org_domain, :string
Lo pense también pero como Lakatan tiene una proyección de ir sumando integraciones decidimos que lo mejor era mantener las cosas que tenían que ver con integraciones alejadas de los modelos originales para que esté mas ordenado y al final el dominio de la organización sólo le importa a la API de Google

2021-01-20 16:21 UTC, yuval-linker commented on app/javascript/api/index.js
> +  const newConfig = { ...config };
Sinceramente lo copié de mute pero en realidad no sé si es necesario

2021-01-20 18:44 UTC, jgmontoya commented on app/javascript/api/index.js
> +  const newConfig = { ...config };
No es tan relevante, mi intuición es hacerlo de la forma más simple primero pero en realidad puedes dejarlo como te parezca mejor.

2021-01-20 18:52 UTC, jgmontoya commented on db/migrate/20210114192244_add_org_domain_to_integrations.rb
> +    add_column :integrations, :org_domain, :string
El dominio de la organización es naturalmente algo inherente a la organización o no? Digo, en términos de órden es el primer lugar donde iría a buscarlo si supiera que se está guardando ese atributo. 

Encuentro rara la decisión además considerando que no veo tan poco probable que en el futuro se use con otras integraciones. Igual si es algo que ya discutieron y decidieron dejar así está bien. ¿Es algo que hablaron durante el sprint o quedó escrito en alguna parte? Así como para echarle un ojo a la discusión si quedó en algún lado porque me gustaría entender mejor qué beneficios tiene dejarlo en este otro modelo

2021-01-21 12:38 UTC, yuval-linker commented on db/migrate/20210114192244_add_org_domain_to_integrations.rb
> +    add_column :integrations, :org_domain, :string
En verdad lo hablé sólo con diego. Me dijo que 

> Para mí que quede en la integración, quiero q cada integración tenga su propio sistema de datos y así no manchamos ni quedamos con una organización, equipos o usuarios gigantes. Esto porque cuando empecemos a agregar integraciones, si empezamos a agregar cosas a los equipos van a quedar enormes e inmanejables

Tal vez es algo que se puede discutir entre mas gente.

2021-01-21 15:22 UTC, jgmontoya commented on db/migrate/20210114192244_add_org_domain_to_integrations.rb
> +    add_column :integrations, :org_domain, :string
No dale tranqui, quizás yo estoy siendo excesivamente mañoso nomás.

2021-01-21 15:38 UTC, jgmontoya approved these changes
Buena! Creo que quedó mucho mejor :100:

2021-01-21 16:24 UTC, merged