Feat add users
platanus/lakatan pull request #241
Opened 2021-01-22 22:17 UTC by fprebolledo

### Contexto
No se puedeb agregar usuarios a las organizaciones si no es por active admin o integración con slack.

### Que se está haciendo
Se creó una nueva vista que lista todos los miembros de la organización y que además da la opción de agregar usuarios a esta. Se pueden agreagr usuarios de la siguiente forma:

    1. Ingresar mail, clickear Agregar
    2. Si existe, agregar a la organización y listo
    3. Si no existe, mostrar el campo para el nombre, clickear Agregar
    4. Se crea el usuario con la contraseña random como está descrito y se agrega a la organización

#### Imaegenes/gifts 

![add_org_member_exist](https://user-images.githubusercontent.com/26394880/105554557-5d26f600-5ce6-11eb-8853-95f7d9cd6c48.gif)
![add_org_member_noexists](https://user-images.githubusercontent.com/26394880/105554566-5ef0b980-5ce6-11eb-8058-546176fdb485.gif)

2021-01-22 22:26 UTC, monkeyci commented on spec/controllers/api/v1/users_controller_spec.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Layout/EmptyLinesAroundBlockBody: Extra empty line detected at block body beginning.

2021-01-22 22:26 UTC, monkeyci commented on spec/controllers/api/v1/users_controller_spec.rb
> +
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Layout/TrailingEmptyLines: 1 trailing blank lines detected.

2021-01-22 22:26 UTC, monkeyci commented on app/javascript/components/addUser.vue
> +              organization_id: Number(this.organizationId),
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Identifier 'organization_id' is not in camel case  camelcase

2021-01-22 22:26 UTC, monkeyci commented on app/javascript/components/addUser.vue
> +              user_id: Number(user.data.data.id),
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Identifier 'user_id' is not in camel case          camelcase

2021-01-22 22:26 UTC, monkeyci commented on app/javascript/components/addUser.vue
> +          organization_id: Number(this.organizationId),
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Identifier 'organization_id' is not in camel case  camelcase

2021-01-22 22:26 UTC, monkeyci commented on app/javascript/components/addUser.vue
> +          user_id: Number(this.getUserByEmail().id),
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Identifier 'user_id' is not in camel case          camelcase

2021-01-22 22:31 UTC, fprebolledo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Desplegar miembros de una organización y añadir formulario](https://trello.com/c/xL26Dq6O/201-desplegar-miembros-de-una-organizaci%C3%B3n-y-a%C3%B1adir-formulario)

2021-01-25 13:07 UTC, AndresGarciadelaHuerta requested changes
Buen PR 👏  te dejo algunos comentarios y posibles cambios, dime que opinas

2021-01-25 13:07 UTC, AndresGarciadelaHuerta commented on app/javascript/components/addUser.vue
> +      } else {
El `await orgMembersRequests.createOrganizationMember` y el `this.resetSettings();` se repiten para los dos flujos posibles, quizás se podría dejarlos una vez y que el `try` sólo haga la creación del usuario, que opinas?

2021-01-25 13:07 UTC, AndresGarciadelaHuerta commented on app/javascript/views/Homepage.vue
> +import addUser from '../components/addUser';
Tengo la duda de si debiese ser `AddUser` con mayúscula 🤔

2021-01-25 13:07 UTC, AndresGarciadelaHuerta commented on app/javascript/views/Homepage.vue
> +      return users.map(user => ({ id: user.id, ...user.attributes }));
Lo mismo de antes, no entendí porque es necesario el `map` 😄

2021-01-25 14:32 UTC, fprebolledo commented on app/javascript/components/addUser.vue
> +      return users.map(user => ({ id: user.id, ...user.attributes }));
Esto es porque cada user de esta lista es de la forma: `user: { id: 1, attributes: { name: juana, email: juana@platan.us }}`, sin embargo la card que está hecha en vue y que usé utiliza el usuario como si estuviera así : `user: { id: 1, name: juana, email: juana@platan.us}`, por eso lo tuve que hacer

2021-01-25 14:33 UTC, fprebolledo commented on app/javascript/components/addUser.vue
> +        if (this.name.length > 0) {
ooh creo que sí. Lo probaré.

2021-01-25 14:36 UTC, AndresGarciadelaHuerta commented on app/javascript/components/addUser.vue
> +      return users.map(user => ({ id: user.id, ...user.attributes }));
perfect, ahí lo entendí 👍

2021-01-25 14:37 UTC, fprebolledo commented on app/javascript/views/Homepage.vue
> +import addUser from '../components/addUser';
Seguí esta convención 
![imagen](https://user-images.githubusercontent.com/26394880/105720008-b1f28880-5f01-11eb-84ae-6ac38c04df63.png)

2021-01-25 14:39 UTC, fprebolledo commented on app/javascript/views/Homepage.vue
> +      return users.map(user => ({ id: user.id, ...user.attributes }));
de hecho acá creo que está demás, se me pasó.

2021-01-25 16:59 UTC, fprebolledo commented on app/javascript/components/addUser.vue
> +        if (this.name.length > 0) {
Ahora lo pensé mejor, pero si solo lo pongo así, en el else tendría que agregar otro if
 `else: { if !this.orMemberNotExists {
 hacer la consulta } }`

2021-01-25 18:53 UTC, AndresGarciadelaHuerta approved these changes
🎉

2021-01-25 18:55 UTC, merged