Activate deactivate google groups
platanus/lakatan pull request #242
Opened 2021-01-26 13:43 UTC by yuval-linker

### Contexto
En Lakatan se agregó la integración para sincronizar con equipos de Google pero no existe la opción de poder elegir qué grupos se sincronizan.
### Qué se está haciendo
Se añade la opción para poder activar y desactivar un grupo en la integración de Google. Para esto:

1. Se mueve la información de la integración de google a su propio modelo `google_integration`
2. Se crea el modelo `active_google_group` para poder saber qué grupos están activos
3. Se añaden 3 componentes a `googleIntegration.vue` de autorización, grupos y desativar la integración.
4. Se crean endpoints, controllers y se modifica la store para poder manejar estos modelos
5. Se arreglan ciertos errores que existían con la implementación de la integración

### En particular hay que revisar
Que la arquitectura de la solución sea buena y eficiente (en especial en front).

2021-01-26 13:43 UTC, yuval-linker commented
![](https://github.trello.services/images/mini-trello-icon.png) [Se puede activar o desactivar el google group por equipo](https://trello.com/c/rq6mZxWz/192-se-puede-activar-o-desactivar-el-google-group-por-equipo)

2021-01-27 12:27 UTC, GabrielLyonB requested changes
En general se ve bien pero tengo algunos comentarios.
Lo primero es que es PR es bastante grande (yo tiendo a tener este problema y hay que esforzarse por hacer PR más chicos para que se revisen más rápido y con mayor detalle).
Lo segundo, revise varios archivos en distintos commits varias veces. En general eso es mala práctica. Lo que intentamos hacer es usar [`git rebase`](https://plata.news/blog/manteniendo-la-historia-limpia-usando-git-rebase/). Te va a pasar que vas a ver comentarios que te dejé que no después corriges (eso entorpese la corrección para el que corrige y el que envía).
Tercero y en línea con lo anterior. Yo intento hacer lo commits lo más atómicos posibles: me da lo mismo que sean 15 commits para 15 archivos porque si después tengo que agregar algo a un archivo pasado es mucho más fácil identificarlo para el `git rebase`. Además, con esto me aseguro de que se entienda el commit y que no voy a commitear dos veces un mismo archivo.

2021-01-27 12:27 UTC, GabrielLyonB commented on app/javascript/components/google/googleGroups.vue
> +      await integrationsApi.updateGoogleGroups({
Lo mismo que te he comentado antes: me parece que va sin el `.then()` si es que tiene un `await`

2021-01-27 12:27 UTC, GabrielLyonB commented on app/javascript/components/google/googleGroups.vue
> +      await integrationsApi.updateGoogleGroups({
lo mismo que el anterior

2021-01-27 12:27 UTC, GabrielLyonB commented on app/javascript/components/google/googleGroups.vue
> +          org => Number(org.id) === Number(orgId),
es necesario el `Number`?

2021-01-27 12:27 UTC, GabrielLyonB commented on app/javascript/store/index.js
> +        .then((response) => {
lo mismo await/then

2021-01-27 12:27 UTC, GabrielLyonB commented on tailwind.config.js
> +    maxHeight: {
está bien agregar estas configuraciones globales? le preguntaría a memo

2021-01-27 12:27 UTC, GabrielLyonB commented on app/controllers/api/v1/google_integrations_controller.rb
> +  def activate_organization
Vuelvo a mencionar lo que dije antes: creo que todo esto debe ir en otro API Controller. Sobre todo si tiene una creación. Aunque siempre puede estar equivocado ...

2021-01-27 12:27 UTC, GabrielLyonB commented on app/controllers/api/v1/google_integrations_controller.rb
> +  def deactivate_organization
lo mismo

2021-01-27 12:27 UTC, GabrielLyonB commented on app/javascript/components/google/googleGroups.vue
> +      await this.$store.dispatch('updateActiveGoogleGroups', {
lo mismo de await/then

2021-01-27 12:27 UTC, GabrielLyonB commented on app/javascript/components/google/googleGroups.vue
> +      await this.$store.dispatch('updateActiveGoogleGroups', {
lo mismo que antes

2021-01-27 12:27 UTC, GabrielLyonB commented on app/javascript/components/google/googleGroups.vue
> +      await integrationsApi.deactivateOrganization({ organizationId: this.organizationId })
lo mismo que antes

2021-01-27 12:27 UTC, GabrielLyonB commented on app/javascript/components/google/googleGroups.vue
> +    async activateOrganization() {
lo mismo

2021-01-27 12:27 UTC, GabrielLyonB commented on app/javascript/store/index.js
> +        .then((response) => {
lo mismo

2021-01-27 12:30 UTC, yuval-linker commented on app/clients/google_auth_client.rb
> +      redirect_uri: "#{ENV['APPLICATION_HOST']}oauth2/google"
Lo que pasa es que la variable de entorno en heroku termina con `/` y eso hizo que no funcionara en staging por eso lo tuve que cambiar

2021-01-27 12:33 UTC, yuval-linker commented on app/models/google_integration.rb
> +    decrypt(self[:google_credentials])
No porque toma `google_credentials` como la función y no el atributo y hace un stack overflow

2021-01-27 12:39 UTC, yuval-linker commented on tailwind.config.js
> +    maxHeight: {
Es algo de Tailwind 2 pero en Lakatan se está usando Tailwind 1.9 entonces hay que agregarlo a mano

2021-01-27 12:44 UTC, yuval-linker commented on app/serializers/api/v1/google_integration_serializer.rb
> +  def valid
Se puede poner `?` como parte del nombre de un atributo en javascript? Por eso hice como ese "alias" porque despues me complicaba llamar a algo como `google_integration.google_valid?`

2021-01-27 13:37 UTC, yuval-linker commented on app/controllers/api/v1/google_integrations_controller.rb
> +  def get_groups
Pero si los grupos son una relación de `google_integration`, no debería ir en su controlador cambiarla?
Por ejemplo, cuando se cambian los miembros de los equipos de lakatan se cambian en el controlador de `teams` porque es una relación de `has_many through` de los equipos y no en un controlador aparte de `members`

2021-01-27 13:53 UTC, closed without merging