Integration view
platanus/lakatan pull request #38
Opened 2020-10-22 17:46 UTC by aaguirrebena

Se agrega la opción de cambiar la mostrado en la vista homepage. En la navbar hay un icono para mostrar las posibles integraciones y desde integraciones volver a mostar los grupos. Las opciones de integración que aparecen estan harcodeadas.

2020-10-22 18:05 UTC, mrafaeli requested changes
Se ve bien, te comento unos detalles chicos

2020-10-22 19:36 UTC, aaguirrebena commented on app/javascript/components/Integrations.vue
> +      console.log('mira:', name);
Si, este y el resto de logs fueron eliminados en el siguiente commit:
1cfb3de

2020-10-22 19:36 UTC, aaguirrebena commented on app/javascript/components/Option.vue
> +      console.log("To Integration")
Resuelto en:
1cfb3de

2020-10-22 19:48 UTC, aaguirrebena commented on app/javascript/app.vue
> +          <div v-if="currentView === `groups`">
Es por sintaxis, al condicionar el valor de una función por ejemplo (currentView retorna un string), la igualdad debe usar comillas simples, al escribir: `v-if="currentView === "groups""` arroja un error de sintaxis. Ocurre lo mismo con la línea 32 del mismo archivo en el último commit hecho.

2020-10-22 19:53 UTC, Snorlax8 commented on app/javascript/app.vue
> +          <div v-if="currentView === `groups`">
Es verdad lo que dice Alfonso, pero ojo que según yo deberías poder ocupar comillas simples e igual se te soluciona el problema. No debería darte un error de sintaxis si escribes "currentView === 'groups'". Sería mejor dejarlo así, porque efectivamente las comillas oblicuas son para interpolación.

2020-10-22 20:23 UTC, mrafaeli commented on app/javascript/app.vue
> +          <div v-if="currentView === `groups`">
A esas comillas me refería jaja las dejé juntas y se ven iguales, mala mía. pero me refería así 'groups'

2020-10-23 00:10 UTC, aaguirrebena commented on app/javascript/app.vue
> +          <div v-if="currentView === `groups`">
perdon! ajaj no me fije bien, ya estan corregidas!

2020-10-23 17:57 UTC, merged