Slack requests
platanus/lakatan pull request #45
Opened 2020-10-23 17:48 UTC by fhohlberg

En esta Pull Request se implementó el Servicio Slack, llamando directamente a la API que provee la gema 'slack-ruby-client', para la creación de la API de comunicación con frontend que permite sincronizar la aplicación de Lakatan con Slack.

*En esta PR se da por hecho que el token del Workspace de Slack a sincronizar, ya fue recibido y guardado en backend de manera encriptada (branch feat(slack-integration)). Se utiliza un token de un Workspace Test API, creado con fin único de testeos de la aplicación, el cual se encuentra almacenado como variable de entorno.

2020-10-26 02:23 UTC, inmadariaga commented on .gitignore
> +.env.development
no deberia agregarse el env.development al git ignore, no deberia tener nada de informacion comprometedora, se guardan los valores de referencia que estan instanciados en el env.local, ejemplo en `env.development`
`SECRET_KEY=secret_key`
y en `env.local`
`SECRET_KEY=aca va la key real`

2020-10-26 02:23 UTC, inmadariaga commented on app/controllers/api/v1/slacks_controller.rb
> +end
aca no falta una linea de codigo?

2020-10-26 02:24 UTC, inmadariaga commented on app/services/slack_service.rb
> +end
Aca tambien falta una linea?
este servicio se uso usando powertypes?

2020-10-26 02:25 UTC, inmadariaga commented on spec/services/slack_service_spec.rb
> +end
Acá falta una linea según github

2020-10-26 02:26 UTC, inmadariaga reviewed
Ya la revise, solo me surgio la duda del servicio si fue creado con la gema o si es necesario

2020-10-26 14:29 UTC, smargozzini requested changes
Creo que faltan varias cosas en este PR para que esté bien estructurado y sea fácil de revisar.
1. hay archivos que se editan muchas veces en varios commits diferentes. Esto no está mal hasta cierto punto. Se modifica la misma accion varias veces, es mejor subir un commit que explique bien el objetivo final de este archivo, sin subir el paso a paso de comoo se modifica.
2. Hay varios merge que no entiendo por que están en el PR.
3. Hay harto código en español
4. hay algunas funciones muy largas. Estan corriendo los linters en el proyecto? es para que el código siga unas reglas estandar de estilo, lo que hace que sea más fácil de revisar para todos.

2020-10-26 14:29 UTC, smargozzini commented on app/services/slack_service.rb
> +        config.token = ENV['SLACK_API_TOKEN']
te falta identar bien esta linea

2020-10-26 14:29 UTC, smargozzini commented on app/services/slack_service.rb
> +                        workspace_id: workspace[:id ]}
acá también creo que hay problemas de indentación

2020-10-26 14:29 UTC, smargozzini commented on app/services/slack_service.rb
> +        return users
no es necesario escribir el `return`, en ruby por defecto se retorna la ultima linea de una función.
En este caso solo bastaría con `users`

2020-10-26 14:29 UTC, smargozzini commented on app/services/slack_service.rb
> +        return teams
lo mismo acá

2020-10-26 14:29 UTC, smargozzini commented on app/services/slack_service.rb
> +        return members
y acá

2020-10-26 14:29 UTC, smargozzini commented on app/services/slack_service.rb
> +        # deleted_users.delete_if { |user| slack_user_mails.include? user[:email] }
esto está bien comentado?

2020-10-26 14:29 UTC, smargozzini commented on spec/services/slack_service_spec.rb
> +end
falta agregar el test del servicio.
No sé si están testeadno, pero si es el caso deberían agregar los tests.
Si no es el caso, no deberías sunir este archivo.

2020-10-26 14:29 UTC, smargozzini commented on .gitignore
> +.env.development
+1

2020-10-26 14:29 UTC, smargozzini commented on app/controllers/api/v1/slacks_controller.rb
> +  def create
Esta función está demsaido grande. 
No es bueno tener código tan grande, lo hace dificíl de leer.
Te recomiendo modularizar y tratar de genralizar lo más posible.

2020-10-26 14:29 UTC, smargozzini commented on app/controllers/api/v1/slacks_controller.rb
> +  def create
también borraría los comentarios, el código debe ser los suficientemente autoexplicativo.

2020-10-26 14:29 UTC, smargozzini commented on app/controllers/api/v1/slacks_controller.rb
> +    respond_with [{"acciones_exitosas": acciones_exitosas, "acciones_fallidas": acciones_fallidas}]
ojo con el spanglish, hay harto código en español e inglés. La idea es que todo esté en un solo idioma, en este caso inglés.

2020-10-26 15:24 UTC, ClaudioPrieto commented on app/services/slack_service.rb
> +                        workspace_id: workspace[:id ]}
Hola, creo que revisaste este archivo en un commit mas antiguo! Perdon lo desordenado, pero nos complicamos porque somos dos personas desarrollando en el mismo PR.

2020-10-26 15:24 UTC, ClaudioPrieto commented on app/services/slack_service.rb
> +        # deleted_users.delete_if { |user| slack_user_mails.include? user[:email] }
Esto se cambio en un commit mas nuevo.

2020-10-26 15:31 UTC, ClaudioPrieto commented on app/services/slack_service.rb
> +        config.token = ENV['SLACK_API_TOKEN']
Arreglado!

2020-10-26 15:31 UTC, ClaudioPrieto commented on app/services/slack_service.rb
> +        return users
Cambie este y el resto de funciones tambien.

2020-10-26 15:35 UTC, ClaudioPrieto commented on .gitignore
> +.env.development
Arreglado.

2020-10-26 15:41 UTC, ClaudioPrieto commented on spec/services/slack_service_spec.rb
> +end
Elimine este archivo por mientras, la idea es tener tests mas adelante!

2020-10-26 15:42 UTC, ClaudioPrieto commented on spec/services/slack_service_spec.rb
> +end
Se elimino este archivo.

2020-10-26 16:10 UTC, smargozzini requested changes

2020-10-26 16:10 UTC, smargozzini commented on app/services/slack_service.rb
> +  def execute_actions(actions_list)
creo que esta función sigue siendo muy grande

2020-10-26 16:21 UTC, ClaudioPrieto commented on app/services/slack_service.rb
> +end
Si, se genero el servicio con Power Types!

2020-10-26 23:12 UTC, fhohlberg commented
@smargozzini 
En el último commit: 
- Se corrieron los linters del proyecto
- Se arreglo el spanglish
- Se acortaron funciones muy largas

** los merge se deben a que, como el trabajo es integrativo, se debieron sacar ramas de esta misma rama y así poder trabajar de forma paralela, editando los mismos archivos, con el fin de dejar todo lo relacionado a un mismo _feat_ en una sola rama para hacer el PR.

2020-10-27 13:21 UTC, smargozzini approved these changes
un mini comentario más. Lo dejo aprobado igual. 👍

2020-10-27 13:32 UTC, merged