docs(slack-integrations) added documentation for api integrations con…
platanus/lakatan pull request #50
Opened 2020-10-29 15:38 UTC by inmadariaga

…troller

2020-10-29 15:44 UTC, mrafaeli requested changes

2020-10-29 15:44 UTC, mrafaeli commented on swagger/v1/swagger.json
> +        "description": "Crea un usuario.",
Ese . está bien al final? Pregunto porque el resto no lo lleva

2020-10-29 15:44 UTC, mrafaeli commented on swagger/v1/swagger.json
> +        "summary": "Crea una Integration",
Suena raro el spanglish jaja, `Integración` mejor?

2020-10-29 15:44 UTC, mrafaeli commented on swagger/v1/swagger.json
> +        "description": "Retorna la lista de las integraciones, como solo se puede integrar con 1 workspace de slack, debe retornar solo 1 integration",
idem con lo de `Integration`

2020-10-29 15:44 UTC, mrafaeli commented
No cacho muy bien el contexto, pero te dejo unos comentarios que me hicieron un poquito de ruido.

2020-10-29 16:19 UTC, inmadariaga commented on swagger/v1/swagger.json
> +        "description": "Crea un usuario.",
no esta bien, lo corrijo altiro

2020-10-29 16:19 UTC, inmadariaga commented on swagger/v1/swagger.json
> +        "summary": "Crea una Integration",
corregido

2020-10-29 16:20 UTC, inmadariaga commented on swagger/v1/swagger.json
> +        "description": "Retorna la lista de las integraciones, como solo se puede integrar con 1 workspace de slack, debe retornar solo 1 integration",
corregido

2020-10-30 02:25 UTC, fhohlberg approved these changes
todo ok!

2020-10-30 19:14 UTC, merged