fix(components/slackChange): fix changes algorithm so it works properly
platanus/lakatan pull request #62
Opened 2020-11-03 18:55 UTC by Snorlax8

- Se corrigieron diferentes errores de manera en que ahora en el segundo paso efectivamente se muestren sólo los cambios que corresponden.
- Si se acepta la eliminación de un equipo, no se mostrarán los cambios en sus membresías: 
![grupo1b](https://user-images.githubusercontent.com/14048037/98028450-e36d2380-1dec-11eb-93c9-df81211f071b.png)
![grupo1a](https://user-images.githubusercontent.com/14048037/98028453-e49e5080-1dec-11eb-8203-278716e76515.png)

![grupo2b](https://user-images.githubusercontent.com/14048037/98028481-ec5df500-1dec-11eb-81cd-12214c480bd8.png)

2020-11-06 17:14 UTC, mrafaeli requested changes
Hola! En general creo que está un poquito enredado. Sería bueno reutilizar algunas propiedades que se repiten y usar computed además de métodos. Los computed te permiten acceder a información que ya se calculó, así no tienes que volver a computar el resultado como en los métodos cada vez que llamas la función

2020-11-06 17:14 UTC, mrafaeli commented on app/javascript/components/slackChange.vue
> +      }
esto creo que queda mejor como:
```ruby
const team = member.attributes.team.slack_id || member.attributes.team.id;
const local = !!member.attributes.team.slack_id
```
Me suena a que el team y local debiesen ser propiedades computed porque se usa en varios lados. Asi no hay que estar pasándolo como parámetro

2020-11-06 17:14 UTC, mrafaeli commented on app/javascript/components/slackChange.vue
> +        this.allOld(user, team, local);
esos 3 me tincan que quedarían mejor en un computed (user, team y local)

2020-11-06 17:14 UTC, mrafaeli commented on app/javascript/components/slackChange.vue
>      },
idem

2020-11-07 01:35 UTC, Snorlax8 commented on app/javascript/components/slackChange.vue
>      },
El problema es que member no existe fuera de la arrow function asociada a la constante team, por lo que la primera línea causaría un error. De todas maneras, limpié un poco esta función y quedó más concisa. Gracias!

2020-11-07 01:37 UTC, Snorlax8 commented on app/javascript/components/slackChange.vue
> +        this.allOld(user, team, local);
Debido a unos cambios en las funciones, ya no se necesita local. Sin embargo, no creo que las variables podrían ir en computed, pues cambian todo el tiempo. User y Team no tienen un valor fijo, si no que van tomando un valor distinto en la medida en que se itera sobre una lista.

2020-11-07 02:03 UTC, Snorlax8 commented on app/javascript/components/slackChange.vue
> +      }
Utilicé la primera línea que me sugieres, gracias! Local ya no se utiliza y, como expliqué en otro comentario, no creo que puedan ir en computed.

2020-11-07 02:07 UTC, merged