Implement jobs for Slack changes request
platanus/lakatan pull request #87
Opened 2020-11-09 15:53 UTC by ClaudioPrieto

Se agregan dos requests al controlador de Slack, la primera solicita los cambios que hay en el workspace de slack actualmente configurado lo que llama a que se ejecute un job que hace todas las request a la API de Slack. La segunda request recibe un id y retorna la informacion de la sincronizacion asociada a ese id, lo cual es el status y en el caso de que el job ya a terminado, la lista con los cambios.

2020-11-09 16:19 UTC, smargozzini requested changes
algunos comentarios

2020-11-09 16:19 UTC, smargozzini commented on app/controllers/api/v1/slacks_controller.rb
> +  # before_action :authenticate_user!
se pasó esto

2020-11-09 16:19 UTC, smargozzini commented on config/sidekiq.yml
> +  :concurrency: 20
porque este cambio?

2020-11-09 16:19 UTC, smargozzini commented on spec/jobs/syncronize_slack_job_spec.rb
> +end
faltó este test

2020-11-09 16:19 UTC, smargozzini commented on spec/models/slack_change_spec.rb
> +end
faltó este test

2020-11-09 16:41 UTC, fhohlberg approved these changes
todo ok!

2020-11-09 17:03 UTC, ClaudioPrieto commented on app/controllers/api/v1/slacks_controller.rb
> +  # before_action :authenticate_user!
Arreglado!

2020-11-09 17:07 UTC, ClaudioPrieto commented on config/sidekiq.yml
> +  :concurrency: 20
La verdad me estaba guiando por la guia de sidekiq que tienen en platanus, igualmente baje el concurrency de ambos a 5.

2020-11-09 18:17 UTC, smargozzini commented
Faltarían los tests y esta ok.

2020-11-10 01:54 UTC, ClaudioPrieto commented
Agregue ambos test, pero tengo hartas dudas con el test del job porque solo verifica que se agregue a la cola. En el caso del test del modelo agregue que se valide solo el status porque changes_list es nulo cuando se crea.

2020-11-10 16:46 UTC, smargozzini approved these changes

2020-11-10 17:11 UTC, merged